name: Docker Build/Publish Image 
on:  
  push:    
    branches: [ main ]  
jobs:   
  build:    
    runs-on: ubuntu-latest
    env:         
      DOCKER_IMAGE: tho861998/mmsplp     
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      DOCKER_TARGET_PLATFORM: linux/arm64                
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v1          
    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest    
    - name: Prepare           
      id: prepare      
      run: |        
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
        echo ::set-output name=docker_image::${DOCKER_IMAGE}           
    - name: Docker Login         
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}          
    - name: Run Buildx (push image)            
      run: |        
        docker buildx build \       
        --platform ${{ steps.prepare.outputs.docker_platform }} \       
        --tag ${{ steps.prepare.outputs.docker_image }} \       
        --file . \
        --push
